# Generated by Django 3.1.2 on 2022-01-15 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_title', models.CharField(default='', max_length=255)),
                ('type_description', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(default='', max_length=255)),
                ('department_location', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_lead_name', models.CharField(default='', max_length=255)),
                ('project_title', models.CharField(default='', max_length=255)),
                ('project_submission_date', models.CharField(default='', max_length=255)),
                ('project_duration', models.CharField(default='', max_length=255)),
                ('project_email', models.CharField(default='', max_length=255)),
                ('project_department', models.CharField(default='', max_length=255)),
                ('project_client_name', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_title', models.CharField(default='', max_length=255)),
                ('status_description', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=255)),
                ('role', models.CharField(default='', max_length=255)),
                ('user_mobile', models.CharField(default='', max_length=255)),
                ('user_email', models.CharField(default='', max_length=255)),
                ('user_dob', models.CharField(default='', max_length=255)),
                ('user_image', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('bug_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_reporting', models.CharField(default='', max_length=255)),
                ('user_number', models.CharField(default='', max_length=255)),
                ('user_email', models.CharField(default='', max_length=255)),
                ('bug_name', models.CharField(default='', max_length=255, null=True)),
                ('bug_date', models.CharField(default='', max_length=255)),
                ('bug_level', models.CharField(default='', max_length=255)),
                ('bug_description', models.TextField(default='')),
                ('bug_cost', models.CharField(blank=True, default='', max_length=255)),
                ('bug_image', models.CharField(blank=True, max_length=255, null=True)),
                ('bug_specifications', models.CharField(blank=True, default='', max_length=255)),
                ('bug_priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.bugtype')),
                ('bug_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.project')),
                ('bug_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.status')),
            ],
        ),
    ]
