# Generated by Django 3.1.2 on 2022-01-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id_number', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=255)),
                ('message', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
